name: local_storage_cache
description: A comprehensive Flutter package for managing local storage and caching with advanced features like encryption, TTL (Time-To-Live), and backup/restore capabilities.
version: 1.0.0
homepage: https://github.com/protheeuz/local-storage-cache.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # assets:
  #   - assets/

plugin:
  platforms:
    android:
      pluginClass: LocalStorageCachePlugin
    ios:
      pluginClass: LocalStorageCachePlugin
    web:
      pluginClass: LocalStorageCachePlugin
    macos:
      pluginClass: LocalStorageCachePlugin
    windows:
      pluginClass: LocalStorageCachePlugin
    linux:
      pluginClass: LocalStorageCachePlugin